spring:
  application:
    name: boot02

logging:
  level:
    root: info
  file:
    name: c:\\java\\logs\\application.log

my:
  name: tester
  fullname: ${my.name} lecture
  secret: ${random.value}